### ISSUE TITLE
Ürün

### ISSUE THREAD

**Issue by Cnr2606** [sikke-official/wallet-web#6]
Skk ye üye olan bir dolu yatırımcıdan biriyim. Ama para çekme olayını nerden nasıl banka hesabına gönderiyoruz bir Bilgi yok. Sıkça sorulan sorular Yada bir yardım menüsü ivedilikle kullanıma açılırsa sorularımız yanıtsız kalmaz.

**Comment by sikke-official** [comment]
Kripto paralar ile ilgili parasal işlemler (Alım Satım) borsalar üzerinde yapılır. Sikke'nin alınıp satılacağı borsa parifix.com çok yakında hizmetinizde olacaktır...
