### ISSUE TITLE
javascript etkin değilken hata uyarısının açıklaması yok

### ISSUE THREAD

**Issue by hasangursoy** [sikke-official/wallet-web#8]
Firefox tarayıcısında noscript ile js kısmen etkin değilken login olmaya çalıştığımda aşağıdaki gibi hata mesajı alıyorum:

Hata Oluştu!
0 - 

![image](https://user-images.githubusercontent.com/341198/42100005-ad170a86-7bc7-11e8-9ac7-ce09c41ad952.png)

**Comment by sikke-official** [comment]
Javascirpt etkin olmadan malesef web cüzdan kullanılamaz.

**Comment by hasangursoy** [comment]
Elbette, ama gösterilen hata hiçbir ipucu vermiyor. İlk gördüğümde siteniz çalışmıyor zannettim.

**Comment by sikke-official** [comment]
Evet haklısınız yarın değiştirelim uygun bir mesaj ile...

**Comment by sikke-official** [comment]
Belirtilen hata düzeltildi...
